// Shared helpers for the framework generators: class naming, property ordering,
// and RULE-ZERO-respecting declaration rendering. Every generator funnels its
// CSS through here, so none of them can emit a property the design didn't set.

import type { CodegenSpec } from '../types.js';
import { declare, cssBlock } from '../rule-zero.js';
import { toCssValue } from '../tokens/mapped-value.js';

/** Mapped-key (camelCase) -> CSS property name, in stable emission order. */
const PROP_CSS: Array<[string, string]> = [
  ['display', 'display'],
  ['flexDirection', 'flex-direction'],
  ['gap', 'gap'],
  ['paddingTop', 'padding-top'],
  ['paddingRight', 'padding-right'],
  ['paddingBottom', 'padding-bottom'],
  ['paddingLeft', 'padding-left'],
  ['width', 'width'],
  ['height', 'height'],
  ['background', 'background'],
  ['color', 'color'],
  ['fontFamily', 'font-family'],
  ['fontSize', 'font-size'],
  ['fontWeight', 'font-weight'],
  ['lineHeight', 'line-height'],
  ['letterSpacing', 'letter-spacing'],
  ['borderWidth', 'border-width'],
  ['borderStyle', 'border-style'],
  ['borderColor', 'border-color'],
  ['borderRadius', 'border-radius'],
];

/** Convert an arbitrary name to a kebab-case CSS class fragment. */
export function kebab(name: string): string {
  const slug = name
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return slug || 'el';
}

/** Convert a name to PascalCase (for component identifiers). */
export function pascal(name: string): string {
  const parts = name.replace(/[^a-zA-Z0-9]+/g, ' ').trim().split(/\s+/);
  const pas = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
  return /^[A-Za-z]/.test(pas) ? pas : `Component${pas}`;
}

export interface RenderedElement {
  className: string;
  declarations: string[];
  texts: string[];
}

/**
 * Assign unique, deterministic class names to every element in the spec and
 * render each element's CSS declarations (RULE ZERO honored). The root element
 * is the first one; its class is derived from the component name.
 */
export function renderElements(spec: CodegenSpec): RenderedElement[] {
  const used = new Map<string, number>();
  const uniqueClass = (base: string): string => {
    const n = used.get(base) ?? 0;
    used.set(base, n + 1);
    return n === 0 ? base : `${base}-${n + 1}`;
  };

  const rootBase = kebab(spec.componentName);

  return spec.elements.map((el, i) => {
    const base = i === 0 ? rootBase : kebab(el.name || `el-${el.nodeId}`);
    const className = uniqueClass(base);
    const declarations: string[] = [];
    for (const [key, cssName] of PROP_CSS) {
      const v = el.mapped[key];
      if (v === undefined) continue; // absent -> never emitted (RULE ZERO)
      declarations.push(declare(cssName, toCssValue(v)));
    }
    return { className, declarations: declarations.filter((d) => d.length > 0), texts: el.texts };
  });
}

/** Render a single `.class { ... }` CSS rule, or "" when the element has no declarations. */
export function cssRule(className: string, declarations: string[]): string {
  if (declarations.length === 0) return '';
  return `.${className} {\n${cssBlock(declarations)}\n}`;
}

/** Escape text content for safe placement inside HTML/JSX. */
export function escapeText(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/** A short banner placed at the top of generated files. */
export function banner(spec: CodegenSpec): string {
  return [
    `Generated by sdet-figma-kit from Figma extraction.`,
    `Component: ${spec.componentName}`,
    `RULE ZERO: properties absent in the design are absent here — review and complete the skeleton.`,
  ].join('\n');
}
